#!/bin/sh
# This file is executed on boot to initialize the system and can also be run by
# the user to start/stop daemons.

DAEMONS="$(basename -s .tire /etc/rc-car/service/*)"

# Read system config
. /etc/rccar.conf

on_boot() {
	echo_color 4 "RC-Car 1.0 booting up $(head -n +1 /etc/issue | awk '{print $1}') [$(uname -rms)]"

	# mount the API filesystem
	echo_color 3 ":: mounting API filesystem..."
	mountpoint -q /proc	|| mount -t proc proc /proc -o nosuid,noexec,nodev
	mountpoint -q /sys	 || mount -t sysfs sys /sys -o nosuid,noexec,nodev
	mountpoint -q /run	 || mount -t tmpfs run /run -o mode=0755,nosuid,nodev
	mountpoint -q /dev	 || mount -t devtmpfs dev /dev -o mode=0755,nosuid
	mkdir -p /dev/pts /dev/shm
	mountpoint -q /dev/pts || mount -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
	mountpoint -q /dev/shm || mount -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev

	# initialize system
	echo_color 3 ":: setting up loopback device..."
	/usr/sbin/ip link set up dev lo

	echo_color 3 ":: initializing udev..."
	if [ "$UDEV" = systemd ]; then
		/usr/lib/systemd/systemd-udevd --daemon
		/usr/bin/udevadm trigger --action=add --type=subsystems
		/usr/bin/udevadm trigger --action=add --type=devices
	elif [ "$UDEV" = eudev ]; then
		/usr/bin/udevd --daemon
		/usr/bin/udevadm trigger --action=add --type=subsystems
		/usr/bin/udevadm trigger --action=add --type=devices
	else # use busybox mdev as fallback:
		busybox mdev -s
		echo /sbin/mdev > /proc/sys/kernel/hotplug
	fi

	echo_color 3 ":: setting hostname..."
	echo "$HOSTNAME" >| /proc/sys/kernel/hostname

	echo_color 3 ":: setting keymap..."
	loadkeys $KEYMAP

	echo_color 3 ":: mounting..."
	mount -a
	mount -o remount,rw /
	swapon -a

	echo_color 3 ":: running fsck on partitions..."
	fsck -A -T -C -a
	
	echo_color 3 ":: setting system clock..."
	hwclock --systz

	echo_color 3 ":: starting daemons..."
	for dmn in $ENABLED; do
		default_start all
	done
}

on_shutdown() {
	# stop the default daemons
	echo_color 3 ":: stopping daemons..."
	default_stop all

	# shut down udev
	echo_color 3 ":: shutting down udev..."
	if [ "$UDEV" = systemd ]; then
		killall systemd-udevd
	elif [ "$UDEV" = eudev ]; then
		killall udevd
	fi

	# umount the API filesystem
	echo_color 3 ":: unmounting API filesystem..."
	umount -r /run
	umount -a -r -t nosysfs,noproc,nodevtmpfs,notmpfs
	swapoff -a

	# mount root read-only
	echo_color 3 ":: setting root partition read-only..."
	mount -o remount,ro /
	
	# TERM & KILL all programs
	echo_color 3 ":: killing programs..."
	busybox killall5 -TERM
	sleep 3
	busybox killall5 -KILL

	busybox poweroff
}

on_reboot () {
	# stop the default daemons
	echo_color 3 ":: stopping daemons..."
	default_stop all

	# shut down udev
	echo_color 3 ":: shutting down udev..."
	if [ "$UDEV" = systemd ]; then
		killall systemd-udevd
	elif [ "$UDEV" = eudev ]; then
		killall udevd
	fi

	# umount the API filesystem
	echo_color 3 ":: unmounting API filesystem..."
	umount -r /run
	umount -a -r -t nosysfs,noproc,nodevtmpfs,notmpfs
	swapoff -a

	# mount root read-only
	echo_color 3 ":: setting root partition read-only..."
	mount -o remount,ro /
	
	# TERM & KILL all programs
	echo_color 3 ":: killing programs..."
	busybox killall5 -TERM
	sleep 3
	busybox killall5 -KILL

	busybox reboot
}

default_start() {
	case "$1" in
	all)
		echo_color 2 ":: starting all enabled daemons..."
		for dmn in $ENABLED; do
			default_start "$dmn"
		done;;
	*)
		echo_color 2 ":: starting $1..."
		/etc/rc-car/service/"$1".tire -start;;
	esac
}

default_stop() {
	case "$1" in
	all)
		echo_color 1 ":: stopping all enabled daemons..."
		for dmn in $ENABLED; do
			default_poll all "$dmn" && default_stop "$dmn"
		done;;
	*)
		echo_color 1 ":: stopping $1..."
		/etc/rc-car/service/"$1".tire -stop;;
	esac
}

default_restart() {
	case "$1" in
	all)
		default_stop all
		default_start all;;
	*)
		echo_color 4 ":: restarting $1"
		/etc/rc-car/service/"$1".tire -restart;;
	esac
}

default_poll() {
	case "$1" in
	all)
		pgrep "$2" >/dev/null 2>&1;;
	*)
		echo_color 4 ":: polling $1..."
		/etc/rc-car/service/"$1".tire -poll &&
		(echo_color 2 ":: $1 is running."; return 0) ||
		(echo_color 1 ":: $1 is not running."; return 1)
	;;
	esac
}

echo_color() {
	color="$1"
	shift
	printf "\\033[1;3%sm%s\\033[00m\\n" "$color" "$*"
}


#===================
# handle arguments
case "$1" in
	init)
		on_boot;;
	shutdown)
		on_shutdown;;
	reboot)
		on_reboot;;
	start)
		default_start "$2";;
	stop)
		default_stop "$2";;
	restart)
		default_restart "$2";;
	poll)
		default_poll "$2";;
	''|list)
		for dmn in $DAEMONS; do
			if default_poll "$dmn" >/dev/null 2>&1; then
				echo_color 2 [X] "$dmn"
			else
				echo_color 0 [ ] "$dmn"
			fi
		done;;
	-h|--help)
		echo "rc-car 1.0"
		echo "Usage: [--help] [--version] <action> [list of daemons]"
		echo
		echo "Actions:"
		echo "rc list                    shows status of all daemons (default action)"
		echo "rc poll [daemon]           polls daemons"
		echo "rc start [daemon]          starts daemons"
		echo "rc stop [daemon]           stops daemons"
		echo "rc restart [daemon]        restarts daemons"
		echo
		echo "System Actions:"
		echo "rc reboot                  reboots the system"
		echo "rc shutdown                shutdown the system"
	;;
esac
